Repository linuxmint/cinnamon-spices-applets, pull requests merged in 2018-03, with the labels that each got.

#1644 sound150@claudiux: v1.3.4 - Multiversion - Bug fixed for Cinnamon 3.4…
  sound150@claudiux/CHANGELOG.md
  sound150@claudiux/README.md
  sound150@claudiux/files/sound150@claudiux/3.4/InstallLanguages.js
  sound150@claudiux/files/sound150@claudiux/3.4/applet.js
  sound150@claudiux/files/sound150@claudiux/3.4/icon.png
  sound150@claudiux/files/sound150@claudiux/3.4/settings-schema.json
  sound150@claudiux/files/sound150@claudiux/CHANGELOG.md
  sound150@claudiux/files/sound150@claudiux/README.md
  sound150@claudiux/files/sound150@claudiux/metadata.json
Labels: In Progress

#1646 Updates multicore-sys-monitor to work on Fedora
  multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/3.4/DataProviders.js
Labels: In Progress

#1651 clipboard-qr@wrouesnel: Fix for Cinnamon 3.6 and use of QR icon
  clipboard-qr@wrouesnel/README.md
  clipboard-qr@wrouesnel/files/clipboard-qr@wrouesnel/applet.js
  clipboard-qr@wrouesnel/files/clipboard-qr@wrouesnel/icon.png
  clipboard-qr@wrouesnel/files/clipboard-qr@wrouesnel/icons/qr-symbolic.svg
  clipboard-qr@wrouesnel/files/clipboard-qr@wrouesnel/metadata.json
  clipboard-qr@wrouesnel/icon.png
Labels: In Progress

#1657 IcingTaskManager@json: Fix findIndex calls
  IcingTaskManager@json/CHANGELOG.md
  IcingTaskManager@json/files/IcingTaskManager@json/3.4/applet.js
  IcingTaskManager@json/files/IcingTaskManager@json/metadata.json
Labels: In Progress

#1659 multicore-sys-monitor@ccadeptic23: Fix applet geometry bugs.
  multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/3.4/Graphs.js
  multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/3.4/applet.js
Labels: In Progress

#1658 printers@linux-man: Update when closing menu
  printers@linux-man/README.md
  printers@linux-man/files/printers@linux-man/applet.js
  printers@linux-man/files/printers@linux-man/metadata.json
Labels: In Progress

#1660 multicore-sys-monitor@ccadeptic23: Fix not everything scaling for HiDPI.
  multicore-sys-monitor@ccadeptic23/files/multicore-sys-monitor@ccadeptic23/3.4/Graphs.js
Labels: In Progress

#1661 Updated Ukrainian translation for weather@mockturtl.
  weather@mockturtl/files/weather@mockturtl/po/uk.po
Labels: In Progress

#1632 placesCenter@scollins: applet.js - Scrollview added to the user secti…
  placesCenter@scollins/files/placesCenter@scollins/applet.js
Labels: APPROVAL BY AUTHOR NEEDED, In Progress

#1662 printers@linux-man: "Reload Applet" and "Restart CUPS" buttons on configuration
  printers@linux-man/README.md
  printers@linux-man/files/printers@linux-man/applet.js
  printers@linux-man/files/printers@linux-man/metadata.json
  printers@linux-man/files/printers@linux-man/po/printers@linux-man.pot
  printers@linux-man/files/printers@linux-man/po/pt.po
  printers@linux-man/files/printers@linux-man/settings-schema.json
Labels: In Progress

#1665 Added missed lines into Ukrainian translation of weather@mockturtl.
  weather@mockturtl/files/weather@mockturtl/po/uk.po
Labels: In Progress

#1667 Ukrainian translation for sticky@scollins.
  sticky@scollins/files/sticky@scollins/po/uk.po
Labels: In Progress

#1666 [bash-sensors@pkkk] Multi-instances support
  bash-sensors@pkkk/files/bash-sensors@pkkk/applet.js
  bash-sensors@pkkk/files/bash-sensors@pkkk/metadata.json
Labels: In Progress

#1669 sticky@scollins: Added fr.po - French translation
  sticky@scollins/files/sticky@scollins/po/fr.po
Labels: In Progress

#1670 Cinnamenu@json: pt_PT translation
  Cinnamenu@json/files/Cinnamenu@json/po/pt_PT.po
Labels: In Progress

#1675 workspace-grid@hernejj: Fix for Cinnamon 3.8
  workspace-grid@hernejj/files/workspace-grid@hernejj/applet.js
Labels: In Progress

#1643 cryptocoin@guantanamoe: unlimited instances and multiple coins
  cryptocoin@guantanamoe/files/cryptocoin@guantanamoe/applet.js
  cryptocoin@guantanamoe/files/cryptocoin@guantanamoe/metadata.json
  cryptocoin@guantanamoe/files/cryptocoin@guantanamoe/settings-schema.json
Labels: APPROVAL BY AUTHOR NEEDED, In Progress

#1703 Cinnamenu@json: Fix exported variables, add Spanish translation
  Cinnamenu@json/files/Cinnamenu@json/constants.js
  Cinnamenu@json/files/Cinnamenu@json/fuzzy.js
  Cinnamenu@json/files/Cinnamenu@json/po/es.po
  Cinnamenu@json/files/Cinnamenu@json/utils.js
Labels: In Progress

#1702 IcingTaskManager@json: Fix exported variables
  IcingTaskManager@json/files/IcingTaskManager@json/3.4/constants.js
  IcingTaskManager@json/files/IcingTaskManager@json/3.4/utils.js
Labels: In Progress

#1704 windowlist@cobinja.de Fix grouping/ungrouping not taking effect
  windowlist@cobinja.de/files/windowlist@cobinja.de/3.2/applet.js
Labels: In Progress

#1705 weather@mockturtl: Update es.po
  weather@mockturtl/files/weather@mockturtl/po/es.po
Labels: In Progress

#1701 Remove broken applet sports-update@pavanred, update CODEOWNERS
  .github/CODEOWNERS
  sports-update@pavanred/files/sports-update@pavanred/applet.js
  sports-update@pavanred/files/sports-update@pavanred/icon-football.png
  sports-update@pavanred/files/sports-update@pavanred/images/icon-americanfootball.png
  sports-update@pavanred/files/sports-update@pavanred/images/icon-baseball.png
  sports-update@pavanred/files/sports-update@pavanred/images/icon-basketball.png
  sports-update@pavanred/files/sports-update@pavanred/images/icon-cricket.png
  sports-update@pavanred/files/sports-update@pavanred/images/icon-football.png
  sports-update@pavanred/files/sports-update@pavanred/images/icon-golf.png
  sports-update@pavanred/files/sports-update@pavanred/images/icon-icehockey.png
  sports-update@pavanred/files/sports-update@pavanred/images/icon-motorsport.png
  sports-update@pavanred/files/sports-update@pavanred/images/icon-tennis.png
  sports-update@pavanred/files/sports-update@pavanred/json_parse.js
  sports-update@pavanred/files/sports-update@pavanred/liveScore.js
  sports-update@pavanred/files/sports-update@pavanred/manifest
  sports-update@pavanred/files/sports-update@pavanred/metadata.json
  sports-update@pavanred/files/sports-update@pavanred/settings-schema.json
  sports-update@pavanred/files/sports-update@pavanred/settings.js
  sports-update@pavanred/icon.png
  sports-update@pavanred/info.json
  sports-update@pavanred/screenshot.png
Labels: APPLET REMOVAL

#1713 cryptocoin@guantanamoe: applet icon
  cryptocoin@guantanamoe/files/cryptocoin@guantanamoe/applet.js
  cryptocoin@guantanamoe/files/cryptocoin@guantanamoe/metadata.json
  cryptocoin@guantanamoe/files/cryptocoin@guantanamoe/settings-schema.json
Labels: APPROVAL BY AUTHOR NEEDED

#1521 [[Feature]] Display World Times in a Non-Bold Font Style – calendar@simonwiles.net
  calendar@simonwiles.net/files/calendar@simonwiles.net/applet.js
Labels: APPROVAL BY AUTHOR NEEDED

#1522 [[Feature]] Add Ability to Assign Key Command to Activate Applet Click Behavior – calendar@simonwiles.net
  calendar@simonwiles.net/files/calendar@simonwiles.net/applet.js
  calendar@simonwiles.net/files/calendar@simonwiles.net/settings-schema.json
Labels: APPROVAL BY AUTHOR NEEDED

#1716 Revert "IcingTaskManager@json: Fix exported variables (#1702)"
  IcingTaskManager@json/files/IcingTaskManager@json/3.4/constants.js
  IcingTaskManager@json/files/IcingTaskManager@json/3.4/utils.js
Labels: In Progress

#1720 sound150@claudiux: v1.4.0
  sound150@claudiux/CHANGELOG.md
  sound150@claudiux/files/sound150@claudiux/2.8/applet.js
  sound150@claudiux/files/sound150@claudiux/3.4/applet.js
  sound150@claudiux/files/sound150@claudiux/CHANGELOG.md
  sound150@claudiux/files/sound150@claudiux/metadata.json
Labels: In Progress

#1721 placesCenter@scollins - fr.po - French translation
  placesCenter@scollins/files/placesCenter@scollins/po/fr.po
Labels: In Progress

#1719 temperature@fevimu: Fix memory leak, refactor
  temperature@fevimu/.eslintrc.json
  temperature@fevimu/.gitignore
  temperature@fevimu/files/temperature@fevimu/applet.js
  temperature@fevimu/files/temperature@fevimu/po/bg.po
  temperature@fevimu/files/temperature@fevimu/po/da.po
  temperature@fevimu/files/temperature@fevimu/po/de.po
  temperature@fevimu/files/temperature@fevimu/po/hr.po
  temperature@fevimu/files/temperature@fevimu/po/pt.po
  temperature@fevimu/files/temperature@fevimu/po/ru.po
  temperature@fevimu/files/temperature@fevimu/po/sv.po
  temperature@fevimu/files/temperature@fevimu/po/temperature@fevimu.pot
  temperature@fevimu/files/temperature@fevimu/po/zh_CN.po
  temperature@fevimu/files/temperature@fevimu/settings-schema.json
  temperature@fevimu/gulpfile.js
  temperature@fevimu/info.json
  temperature@fevimu/locale.sh
  temperature@fevimu/package.json
  temperature@fevimu/yarn.lock
Labels: In Progress

#1714 cryptocoin@guantanamoe: currencies
  cryptocoin@guantanamoe/files/cryptocoin@guantanamoe/accounting.js
  cryptocoin@guantanamoe/files/cryptocoin@guantanamoe/applet.js
  cryptocoin@guantanamoe/files/cryptocoin@guantanamoe/currencies.json
  cryptocoin@guantanamoe/files/cryptocoin@guantanamoe/metadata.json
  cryptocoin@guantanamoe/files/cryptocoin@guantanamoe/settings-schema.json
  cryptocoin@guantanamoe/screenshot.png
Labels: APPROVAL BY AUTHOR NEEDED, In Progress

#1724 temperature@fevimu: Updated pt-PT translation
  temperature@fevimu/files/temperature@fevimu/po/pt.po
Labels: In Progress
